[package]
name = "olin-tests"
version = "0.1.0"
authors = ["Christine Dodrill <me@christine.website>"]
edition = "2018"

[dependencies]
chrono = "0.4"
http = "0.1"
httparse = "1.3.2"
log = "0"
maj = { version = "0", default-features = false }
olin = { path = "../olin" }
